[package]
name = "fas-rs"
version = "1.8.0"
edition = "2021"
description = "Frame-aware scheduling binary"
authors = ["shadow3"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/shadow3aaa/fas-rs"

[workspace]
exclude = ["zygisk/rust"]

[dependencies]
likely_stable = "0.1.2"
parking_lot = "0.12.1"
log = "0.4.20"
anyhow = "1.0.79"
thiserror = "1.0.56"
inotify = { version = "0.10.2", default-features = false }
libc = "0.2.151"
async-trait = "0.1.77"
binder = { package = "binder_ndk", version = "0.2.0" }
lazy_static = "1.4.0"
once_cell = "1.19.0"
flexi_logger = "0.27.3"
serde_derive = "1.0.193"
toml = "0.8.8"
serde = "1.0.193"

[build-dependencies]
anyhow = "1.0.79"
toml = "0.8.8"
serde = "1.0.193"
serde_derive = "1.0.193"

[profile.dev]
overflow-checks = false

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 's'
strip = true
panic = "abort"
