名字: ci-build

在:
推:
分支: [ "master" ]
query为空pull_request:
分支: [ "master" ]

env:
  CARGO_TERM_COLOR: 总是

工作:
建筑:

    runs-on: ubuntu-latest

步骤:
    - 用途: actions/checkout@v3
    - 名字: 设置ndk
跑: |
ndk_url=$（wget-qO-https：//github. com/android/ndk/releases/最新|grep-e'https://dl.google.com/android/repository/android-ndk-.*-linux.zip'|sed-n's/.*<a href="\（[^"]*\）".*\1/p'）
wget -O ndk.zip $ndk_url -nv
mkdir ~/ndk_temp
解压缩ndk. zip-d~/ndk_temp 2>&1>/dev/null
mv ~/ndk_temp/*/* ~/ndk_temp

    - 名字: 安装防锈工具链
跑: |
每晚
rustup目标添加aarch64-linux-android armv7-linux-androideabi x 86_64-linux-android i686-linux-android

    - 名字: 安装货物ndk
跑: 货物安装货物-ndk
    
    - 名字: 其他部门
跑: |
sudo apt更新
sudo apt install gcc-multilib git-lfs
git lfs拉

    - 名字: 建筑
跑: |
导出ANDROID_NDK_HOME=$（realpath~/NDK_temp）
导出ANDROID_NDK_ROOT=$ANDROID_NDK_HOME
chmod +x ./make.sh
./make.sh build --release -v

    - 名字: 上载
用途: actions/upload-artifact@v3.1.3
与:
名字: fas-rs(ci-build)
路径: output/.temp
